services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    # Ensure UTF-8 encoding to support Thai characters and others
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-epic_pizza_dev}"
      POSTGRES_INITDB_ARGS: >-
        --encoding=UTF8 --lc-collate=C --lc-ctype=C
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - '127.0.0.1:6379:6379'
volumes:
  pgdata:
